# Generated by Django 3.2.2 on 2021-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicBeats', '0002_song_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='credit',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
