# Generated by Django 3.2.2 on 2021-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicBeats', '0006_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('music', models.CharField(max_length=1000000)),
            ],
        ),
    ]
